### ISSUE TITLE
Markdown font-size styles cause cursor placement and rendering issues

### ISSUE THREAD

**Issue by bryanbraun** [promek/wombat-dark-syntax#2]
The [heading font size styles in markdown.less](https://github.com/promek/wombat-dark-syntax/blob/master/styles/languages/markdown.less#L28) causes issues using the cursor in markdown files, making it difficult to select text or jump to specific locations in the file. It also can mess up rendering a bit, causing overlapping etc. See screenshot below (note that the cursor doesn't fit on the line of the heading, and that some elements are rendered too close to each other):

![image](https://cloud.githubusercontent.com/assets/1256329/16057446/25f69690-3248-11e6-87d5-54e1c2a69e44.png)

I get the reasoning behind font size rules, but Atom has a good markdown preview pane built in, so I'd say it's better to use that than provide a quasi-preview in the text file (which causes glitches like these).

My current temporary workaround is to change these files to render as plain text.

**Comment by promek** [comment]
Thank you for your contribution.
upon request from users, I changed the font style markdown.
You can update your editor.

**Comment by bryanbraun** [comment]
I just updated, and yes, this looks much better. Thanks!
